### ISSUE TITLE
Reseting Limits problem

### ISSUE THREAD

**Issue by Andziaa** [InsightsPlugin/PlotSquaredAddon#3]
Hello, I have installed PlotSquared and WorldEdit extentions.

The problem is: When a player, who used all limit for ex. Hoppers, clears his plot and tries to place hoppers again, then it still shows his previous limit and he can't place that hoppers.

**Comment by FrankHeijden** [comment]
Fixed with v2.1.0! Please note, the addon now requires PlotSquared v6.
